---
- name: restart tftp
  ansible.builtin.service:
    name: tftp
    state: restarted

- name: restart bind
  ansible.builtin.service:
    name: named
    state: restarted

- name: restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: restart dhcpd
  ansible.builtin.service:
    name: dhcpd
    state: restarted

- name: restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
